Timeline add new entry
uoftblueprint/tces pull request #105
Opened 2023-02-28 19:27 UTC by ganeshasapu

# Description
Creates ability to add new notes to timeline for a given employer.

Possible Concerns:
- Relies on the employer page making fetch calls and formatting information before passing into timeline component
- Exact display and formatting (mostly for default look) should be corrected and polished when merging with #91.

Fixes #90 

Display:
<img width="414" alt="Screen Shot 2023-02-28 at 2 22 26 PM" src="https://user-images.githubusercontent.com/62232361/221957497-5ae0a7a3-425c-4273-9fc2-f3523eec8787.png">

Example implementation in employer page:
<img width="466" alt="Screen Shot 2023-02-28 at 2 20 36 PM" src="https://user-images.githubusercontent.com/62232361/221957685-c3c8728c-c589-4e6c-a599-e77f9e160d91.png">

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have run `npm run lint:fix`
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings

2023-03-03 02:43 UTC, jordanjanakievski requested changes
Clinet and Job Postings not displaying correctly after click

![Screenshot 2023-03-02 at 21 43 14](https://user-images.githubusercontent.com/41130718/222618220-9afc84df-a137-4edf-8eeb-6481c02e8818.png)

Everything else is working and looking great

2023-03-04 17:43 UTC, edwardhuahan requested changes
Everything looks great! Just make sure to change that one line of code and it should be good

2023-03-04 17:43 UTC, edwardhuahan commented on client/src/App.tsx
> +        {Communication()}
I would suggest to replace this with `<Communication />`

2023-03-04 19:22 UTC, jordanjanakievski approved these changes
Looks good to me

2023-03-05 15:35 UTC, edwardhuahan commented
Looks great! good style

2023-03-05 15:36 UTC, edwardhuahan approved these changes

2023-03-05 17:58 UTC, thardchi approved these changes
Great job, everything looks good on my end!

2023-03-05 18:21 UTC, merged