#106 create employer individual export
uoftblueprint/tces pull request #124
Opened 2023-03-18 09:52 UTC by ganeshasapu

# Description

Added export of main information for employer object. Also deleted a small thing in ActivityTimeline that was causing me a bug, I don't think it changes any functionality.

Fixes #106 

## Sample curl
*Note this was called after populating employer with address object and timeline notes.
curl --location 'http://localhost:3001/api/employer/6414e9b60646b301070b144c/main' \ --data ''
## Response
{
    "primary_address_id": {
        "_id": "6414e8d30646b301070b1447",
        "street_address": "test123",
        "city": "test123",
        "building_num": 123,
        "province": "Ontario",
        "postal_code": "Test"
    },
    "contacts": [
        {
            "_id": "6414e9b60646b301070b144b",
            "phone_num": "42423",
            "email": "434234",
            "alt_phone_num": null,
            "website": null
        }
    ],
    "secondary_address_id": {
        "_id": "6414e9a40646b301070b144a",
        "street_address": "test123",
        "city": "test123456",
        "building_num": 123,
        "province": "Ontario",
        "postal_code": "Test"
    },
    "timeline": {
        "notes": [
            {
                "text": "'Client 2' was placed in Job 1. dasdasdasdas",
                "category": "PLACEMENTS",
                "timestamp": "2023-03-18T09:45:53.450Z",
                "title": "John Doe Placed Client 2"
            },
            {
                "text": "tester",
                "category": "NOTES",
                "timestamp": "2023-03-18T09:46:41.087Z",
                "title": "John Doe Added Note"
            }
        ]
    },
    "name": "Test"
}

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have run `npm run lint:fix`
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works (Delete if frontend)

2023-03-18 19:28 UTC, kenneth-miura requested changes
Looks great! I have one small note, but it's just a small optimization. Great work!

2023-03-18 19:28 UTC, kenneth-miura commented on server/src/models/employer.model.ts
> +        for (const contact_id of employer.contacts) {
https://www.mongodb.com/docs/manual/reference/operator/aggregation/unwind/ 

I think you can just use this functionality for this rather than looping over. Also (ignore if you already know this), the DB will always be faster at performing an operation than you will be replicating it manually. Most of the time, it will perform some optimization internally making it faster

2023-03-18 22:13 UTC, ganeshasapu commented on server/src/models/employer.model.ts
> +        for (const contact_id of employer.contacts) {
ah did not know about this function, ty for the advice

2023-03-19 18:20 UTC, helen-li requested changes
Looks greatttt - agree with Kenneth and also dropped a small comment

2023-03-19 19:11 UTC, helen-li commented on server/src/models/employer.model.ts
> +          ? await collections.addresses?.findOne({
oh something else just popped up in my mind, might not be in the scope of this ticket but connect this endpoint to the export button on the frontend employer page?

2023-03-19 19:35 UTC, jordanjanakievski reviewed
Apart from Kenneth and Helen's comments, everything looks good to me. Working as advertised.

2023-03-21 01:22 UTC, kenneth-miura commented on server/src/models/employer.model.ts
> +          ? await collections.addresses?.findOne({
idk if u already did but when it's a scope question can u slack dm me & edward lol

2023-03-23 17:27 UTC, kenneth-miura requested changes
did not communicate an expected change, my b

2023-03-23 17:27 UTC, kenneth-miura commented on server/src/models/contact.model.ts
>  export default class Contact {
I don't think I told you but we are deleting contact? We can talk about it during meeting today

2023-03-23 17:27 UTC, kenneth-miura commented on server/src/models/contact.model.ts
>  export default class Contact {
that's my bad

2023-04-02 17:36 UTC, helen-li approved these changes
Quick question below, looks greattt otherwise

2023-04-02 17:36 UTC, helen-li commented on server/package.json
>      "react-router-dom": "^6.7.0",
are these added packages for the server?

2023-04-02 18:42 UTC, jordanjanakievski approved these changes
Looks good. Glad the dev changes were able to be implemented and everything is working smoothly

2023-04-02 20:37 UTC, kenneth-miura requested changes
lgtm style wise

2023-04-02 20:37 UTC, kenneth-miura commented on server/src/routes/employer.routes.ts
> +employersRouter.get("/employer/:id/main", EmployerController.getEmployerMainInfo);
nitpicky but I think you should call it `/export` and call it `getEmployerExportInfo`, since main doesn't really specify what the intended usage is.

2023-04-13 02:29 UTC, kenneth-miura approved these changes
Looks great! Thanks for making those changes I requested.

2023-04-13 02:33 UTC, merged