Mass Client Export as CSV
uoftblueprint/tces pull request #130
Opened 2023-03-20 04:53 UTC by ganeshasapu

# Description
Basically just takes in a query and gets all of the clients that match with all of the relevant info (first_name, last_name, email, phone_num, owner)

Used json2csv module to convert from object to csv file

Fixes #113 

## Sample curl
First create client using: curl --location 'http://localhost:3001/api/client/' \
--header 'Content-Type: application/json' \
--data-raw '{
    "first_name": "Test",
    "last_name": "Test2432432",
    "assignee_id": "6417ded4a36cc75145b7abf3",
    "date_created": "11/02/22",
    "status": "ACTIVE",
    "phone_num": "1234567890",
    "email": "test@gmail.com",
    "note": "JSJDLKASJjkldjalskjdas"

}'

Then get mass client info using: curl --location 'http://localhost:3001/api/client/mass?status=ACTIVE&owner=64176076f365311c668a9bbb&dateFrom=11%2F02%2F21&dateTo=11%2F02%2F24'
## Response
"first_name","last_name","phone_num","email","owner"
"Test","Test2","1234567890","test@gmail.com","email@gmail.com"

## Type of change

- [x] New feature (non-breaking change which adds functionality)

2023-04-07 01:34 UTC, kenneth-miura requested changes
yo idk why this weird package.json stuff keeps happening

2023-04-07 01:34 UTC, kenneth-miura commented on server/package.json
> +    "react": "^18.2.0",
yo why is `react` and `mui` and `react-dom` in the server package.json? Like this keeps happening, any idea why?

2023-04-07 01:34 UTC, kenneth-miura commented on server/src/controllers/client.controller.ts
> +        const jsonData = JSON.stringify(client, null, 2)
fellow 2 space tab enjoyer

2023-04-08 20:29 UTC, helen-li reviewed
Dropped some minor things here and there! Trusting that you already ran and tested locally so I didn't run it myself but overall looks greatt

2023-04-08 20:29 UTC, helen-li commented on server/package.json
> +    "react": "^18.2.0",
same question

2023-04-08 20:29 UTC, helen-li commented on server/src/controllers/client.controller.ts
> +const { debug } = require('../logger')(path.join(__dirname, 'logs'))
```suggestion
const { error, debug } = require('../logger')(path.join(__dirname, 'logs'))
```
should work

2023-04-08 20:29 UTC, helen-li commented on server/src/controllers/client.controller.ts
> +
potentially a dumb question but do we not need to do the `res.setHeader` calls here like done above for individual exports?

2023-04-08 20:29 UTC, helen-li commented on server/src/models/client.model.ts
> +        let pipeline = [
pipeline slay - i didn't run locally but logically made sense reading through

2023-04-10 03:15 UTC, jordanjanakievski approved these changes
Looks good. I am going to approve so you only have to ping Helen after her suggestions.  Otherwise, everything looked good.

2023-04-13 02:58 UTC, ganeshasapu commented on server/src/controllers/client.controller.ts
> +
Yeah it's not needed because I'm using a package that converts the data into a csv file automatically, rather than with the others where I just had the json data and had to send it as a file.

2023-04-13 03:04 UTC, kenneth-miura approved these changes
lgtm

2023-04-13 03:23 UTC, merged