[TCES-65][IN-PROGRESS] Separate Get Job Postings Endpoint into Two Distinct Endpoints for Public and Protected Job Postings
uoftblueprint/tces pull request #132
Opened 2024-12-31 03:21 UTC by williamntlam

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Issue #

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist

Please delete options that are not applicable.

- [ ] My code follows the style guidelines of this project (required)
- [ ] I have performed a self-review of my code (required)
- [ ] I have linted and formatted my code (required)
- [ ] New and existing unit tests pass locally with my changes (required)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

2024-12-31 17:07 UTC, 04kash commented
Thanks @williamntlam ! 
I'm working on adding unit tests for the endpoints implemented so far. For the two endpoints that you worked on in this PR, would you want to add the units within this PR itself or would you prefer to have a separate PR?

2025-01-01 02:40 UTC, williamntlam commented
I can add the unit tests within this PR for the two endpoints. I'll start doing that @04kash!

2025-01-05 18:05 UTC, williamntlam commented
![image](https://github.com/user-attachments/assets/23f2f6e7-0b1f-48a1-b33c-606966270953)

![image](https://github.com/user-attachments/assets/575ce9ae-db09-46c6-a683-8efa12614d94)

Just tested it on my own and the two endpoints seem to work (There is only one non-active job posting). I'll work on adding the unit testing now!

2025-01-05 19:10 UTC, williamntlam commented
Just added unit testing for getting active job posts and getting all job posts. The unit tests consists of the following:

# Summary of Unit Tests for `getAllJobPostsRequestHandler` and `getAllActiveJobPostsRequestHandler`

This summary includes tests for fetching all job posts (normal) and active job posts, covering scenarios like success, pagination, no pagination, and error handling.

---

## **Tests for Normal Job Posts (`getAllJobPostsRequestHandler`)**

1. **Returns 200 on success**: Verifies that the handler responds with a `200` status code when the request is successful.
   ```javascript
   expect(mockRes.statusCode).toBe(200);
   ```

2. **Calls `findAndCountAll` twice**: Ensures both all job posts and active job posts queries are made.
   ```javascript
   expect(spy).toHaveBeenCalledTimes(2);
   ```

3. **Handles pagination correctly**: Tests pagination logic by checking `totalPosts`, `totalPages`, `currentPage`, and paginated data.
   ```javascript
   expect(mockRes.json).toHaveBeenCalledWith({
     allJobPosts: {
       totalPosts: 4,
       totalPages: 2,
       currentPage: 1,
       data: [...],
     },
     publicJobPosts: {
       totalPosts: 3,
       totalPages: 2,
       currentPage: 1,
       data: [...],
     },
   });
   ```

4. **Handles no pagination**: Ensures all job posts are returned when no `page` or `pageSize` is provided.

5. **Handles errors and returns 500**: Simulates an error and checks for `500` status and error message.

---

## **Tests for Active Job Posts (`getAllActiveJobPostsRequestHandler`)**

1. **Returns 200 on success**: Verifies that the handler responds with a `200` status code.

2. **Calls `findAndCountAll` with correct filter**: Ensures the query uses `where: { state: "Active" }`.
   ```javascript
   expect(spy).toHaveBeenCalledWith(expect.objectContaining({ where: { state: "Active" } }));
   ```

3. **Handles pagination correctly**: Confirms `totalPosts`, `totalPages`, `currentPage`, and paginated data for active posts.
   ```javascript
   expect(mockRes.json).toHaveBeenCalledWith({
     publicJobPosts: {
       totalPosts: 3,
       totalPages: 2,
       currentPage: 1,
       data: [...],
     },
   });
   ```

4. **Handles no pagination**: Verifies all active job posts are returned when no pagination parameters are provided.

5. **Handles errors and returns 500**: Simulates an error and ensures proper error response (`500` status and error message).

---

### **Key Points**
- Both handlers handle pagination, no pagination, and error scenarios.
- The tests ensure proper response structures for normal and active job posts.

2025-01-11 21:40 UTC, 04kash requested changes

2025-01-11 21:40 UTC, 04kash commented on server/src/controllers/job_posts/getAllJobPosts.js
>        publicJobPosts: {
Since we now have a separate endpoint to get all active/public job posts I think for the get all job posts endpoint we can just return all job posts.

2025-01-12 21:53 UTC, williamntlam commented on server/src/controllers/job_posts/getAllJobPosts.js
>        publicJobPosts: {
I just fixed the division by zero error and changed the return object so that it only returns allJobPosts without publicJobPosts now. 

Hope that helps! 

William.

2025-01-12 22:01 UTC, 04kash approved these changes

2025-01-12 22:01 UTC, 04kash commented on client/src/components/add-job-post-component/application-form-fields/index.module.css
Just remove all the changes made to the files inside the `client` folder, other than take lgtm!

2025-01-12 22:21 UTC, merged