Linting
uoftblueprint/tces pull request #16
Opened 2022-11-08 22:09 UTC by EclipseIsDead

Addresses Issue #13.

LMK if you want other settings/preferences.

2022-11-08 22:40 UTC, kenneth-miura requested changes
Looks good, can u add something in README.md to tell ppl to run `npm run lint:fix`?

2022-11-17 23:32 UTC, kenneth-miura requested changes
can u also add it to frontend readme

2022-11-20 21:27 UTC, jordanjanakievski approved these changes
Checked the linter in client. Everything looked to me that it worked correctly. This is my first time with a linter this way, but it is very easy to use and find the instructions on how to run it in the README

2022-11-29 15:26 UTC, kenneth-miura approved these changes

2022-11-29 21:10 UTC, merged