Front and back connect
uoftblueprint/tces pull request #29
Opened 2022-11-13 21:59 UTC by jordanjanakievski

Fixes #3 

Creates buttons that enable the frontend to connect to backend APIs. Can send GET and POST requests.

![Screenshot 2022-11-13 at 16 53 27](https://user-images.githubusercontent.com/41130718/201546530-d174af73-e3fa-4230-8378-d59158272114.png)

Additional dependencies added 
In Server: body-parser
In Client: "react-scripts": "4.0.3" needed to be downgraded. Need feedback on this
"start": "WATCHPACK_POLLING=true react-scripts --openssl-legacy-provider start", required to solve client container bug

2022-11-13 22:06 UTC, kenneth-miura commented
Downgrading react-scripts is fine imo

2022-11-14 17:52 UTC, kenneth-miura requested changes
just a Q

2022-11-14 17:52 UTC, kenneth-miura commented on server/index.ts
> +app.use((req, res, next) => {
I'm pretty sure u don't actually need this, and the proxy in the client package.json just works

2022-11-14 17:52 UTC, kenneth-miura commented on server/index.ts
> +app.use((req, res, next) => {
Can u verify this + delete this if the proxy in `client` `package.json` works?

2022-11-16 02:10 UTC, jordanjanakievski commented on server/index.ts
> +app.use((req, res, next) => {
I removed the cors packages in the newest commit. The `package,json` should no longer have cors

2022-11-17 04:47 UTC, helen-li commented on server/index.ts
> +app.use(bodyParser.json());
We have express newer than 4.16 - I believe we don't need bodyParser and can just use `express.json()` here instead to allow parsing of JSON bodies in requests. Feel free to test everything without using bodyParser and remove the dependency if it's unnecessary.

2022-11-17 04:48 UTC, helen-li requested changes
Just one quick minor comment - otherwise everything looks good and works well! Tested in both browser and Postman

2022-11-17 05:44 UTC, jordanjanakievski commented on server/index.ts
> +app.use(bodyParser.json());
Thank you for the feedback. I removed the dependency and everything worked well.

2022-11-17 15:15 UTC, helen-li approved these changes
good to go for me!

2022-11-17 23:29 UTC, kenneth-miura commented on server/index.ts
> +app.use((req, res, next) => {
do u still need this function tho? If the proxy from frontend works.

2022-11-18 04:03 UTC, jordanjanakievski commented on server/index.ts
> +app.use((req, res, next) => {
Just tested and pushed a new commit. I removed the CORS handling since the server and client both connect without the need of it

2022-11-18 15:19 UTC, kenneth-miura approved these changes
lgtm!

2022-11-20 21:21 UTC, merged