TCES-10: Implement backend testing libraries
uoftblueprint/tces pull request #32
Opened 2022-11-20 14:58 UTC by thardchi

# Description

Link to ticket: https://github.com/uoftblueprint/tces/issues/10

Installed jest library and wrote a test to verify that the response from the app.get endpoint is "Hello from server!" and the expected status code is 200.

New devDependencies:
        "@types/jest": "^29.2.3",
        "jest": "^29.3.1"

Fixes # 10

## Sample curl
Ignore if PR does not affect an endpoint.
## Response
Ignore if PR does not affect an endpoint.

## Type of change

# Checklist:

- [ ] I have run `npm run lint:fix`
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works (Delete if frontend)

2022-11-20 16:49 UTC, EclipseIsDead requested changes

2022-11-20 16:49 UTC, EclipseIsDead commented on package.json
> +        "test": "jest"
should probably only have jest in server level package.json

2022-11-20 21:23 UTC, annie951977 requested changes
I agree with Siddarth, looks good otherwise

2022-11-29 21:14 UTC, EclipseIsDead approved these changes
lgtm

2022-12-04 18:58 UTC, annie951977 approved these changes
pog

2022-12-04 22:34 UTC, merged