Create read client
uoftblueprint/tces pull request #33
Opened 2022-11-22 14:29 UTC by ganeshasapu

# Description

Added functionality for reading and creating clients for database

Fixes # (issue/ticket number)

Issue #23 

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

2022-11-23 02:18 UTC, kenneth-miura requested changes

2022-11-23 02:47 UTC, ganeshasapu commented on server/index.ts
> +connectToDatabase()
Does the connectToDatabase function in database.ts replace the one found in client.controller.ts? If so, what would go in the client.controller.ts file?

2022-12-03 20:52 UTC, ganeshasapu commented
Huge props to @helen-li for PR on create-job issue. Looking over that code really helped with working on this issue.

2023-01-15 19:15 UTC, kenneth-miura requested changes
can u move all the backend directories into the src directory

2023-01-16 22:39 UTC, ganeshasapu commented
> can u move all the backend directories into the src directory

Fixed

2023-01-20 02:41 UTC, kenneth-miura approved these changes
lgtm! Also request reviews from ppl + turn this off of being a draft lol

2023-01-25 23:41 UTC, helen-li requested changes
I just skimmed your specific endpoints code (trust you that they are working as intended) & they lgtm! Just left 2 quick comments on schema validation

2023-01-25 23:41 UTC, helen-li commented on server/src/database/conn.ts
> +  await db.command({
No longer needed - the schema validation is now applied in line 30 when you create the collection, so this command here which applies it again becomes redundant. 

Not exactly sure but this might be the solution to the validation error you mentioned?

2023-01-25 23:41 UTC, helen-li commented on server/src/database/conn.ts
>  import { jobSchema } from "./schemas";
Very slight nitpick lol but can you quickly combine these imports into the same line, just so hopefully future PRs that import schemas will just edit one single line instead of having a bunch of lines just for schema imports

2023-01-26 06:26 UTC, jordanjanakievski requested changes
After the validation edit, the backend should run correctly for everyone it should be good to go.

2023-01-26 06:26 UTC, jordanjanakievski commented on server/src/database/conn.ts
>  import { jobSchema } from "./schemas";
I second this

2023-01-26 06:26 UTC, jordanjanakievski commented on server/src/database/conn.ts
> +  await db.command({
[https://uoftblueprint.slack.com/archives/C042ZP2KA65/p1673810562574329](https://uoftblueprint.slack.com/archives/C042ZP2KA65/p1673810562574329)

This code sample on slack should replace this. You can also see how Helen and I implemented it in our PRs

2023-01-26 14:02 UTC, merged