Development Logger
uoftblueprint/tces pull request #35
Opened 2022-11-23 02:53 UTC by jordanjanakievski

Fixes #22 

Creation of a development logger.
We can add the logger to files and output more informational messages instead of `console.log` and label them based on the level of importance

```
levels = {
  error: 0,
  warn: 1,
  info: 2,
  http: 3,
  verbose: 4,
  debug: 5
};
```

Additional dependencies added
In `server/logger`: winston

2022-11-27 21:45 UTC, helen-li reviewed
Looks good overall! The README stuff was really helpful too. Dropped two quick questions :)

2022-11-27 21:45 UTC, helen-li commented on server/logger/index.ts
> +			levels: { [level]: 0 },
quick question out of curiosity - why do we always put 0 as the value here?

2022-11-27 21:45 UTC, helen-li commented on server/logger/index.ts
> +		levels[level] = createLogger({
what are the advantages of creating a logger for each level individually versus creating one logger & changing how we use the logger in our files

2022-11-27 22:20 UTC, jordanjanakievski commented on server/logger/index.ts
> +			levels: { [level]: 0 },
I messed around with the code a bit and ended up removing this line.  The formatting function handles the level so this line was no longer needed

2022-11-27 22:23 UTC, jordanjanakievski commented on server/logger/index.ts
> +		levels[level] = createLogger({
This is my first time setting up a logger, but I noticed the readability on the server code end is clear as the function will simply state the error type. But if there is a better, more flexible way I would be more than happy to look into and implement it

2022-11-28 00:32 UTC, helen-li commented on server/logger/index.ts
> +		levels[level] = createLogger({
gotchu i see! - i was just curious since i don't know much about loggers lol

2022-11-28 00:32 UTC, helen-li approved these changes
thanks jordan lgtm!

2022-11-29 16:37 UTC, ganeshasapu approved these changes
I haven't used loggers before so this was cool to see. Everything works on my end and the ReadMe was very helpful. W PR

2022-11-29 21:10 UTC, EclipseIsDead requested changes
lgtm, small change

2022-11-29 21:10 UTC, EclipseIsDead commented on server/logger/package.json
> +{
I think we only want 1 package.json for the backend, move this to the server package.json

2022-11-30 21:26 UTC, jordanjanakievski commented on server/logger/package.json
> +{
I moved the winston dependency to the server package and left the logger free of dependencies

2022-12-06 02:37 UTC, EclipseIsDead approved these changes

2022-12-07 01:44 UTC, merged