TCES-53 TIM-Timeline Window
uoftblueprint/tces pull request #48
Opened 2024-01-24 00:56 UTC by selintasman

# Description

2024-02-03 22:35 UTC, DanielDervishi reviewed
Great work Selin! The pr should be ready to be merged after these comments are addressed

2024-02-03 22:35 UTC, DanielDervishi commented on client/src/components/timeline-window-component/clientWindow.jsx
> +    />
The search component can be removed from each of the timeline windows (It's been listed as a nice to have for now)

2024-02-03 22:35 UTC, DanielDervishi commented on client/src/components/timeline-window-component/clientWindow.jsx
> +                <Tab label="NOTES" value="4" />
The spacing between different tabs here looks a bit uneven
<img width="495" alt="image" src="https://github.com/uoftblueprint/tces/assets/58835213/f04b3bb1-62f3-4205-ba8c-a8acd09aa60d">

2024-02-03 22:35 UTC, DanielDervishi commented on client/package.json
>      "@emotion/react": "^11.11.1",
Noticed a small bug when clicking the three dots at the top of the timeline window

https://github.com/uoftblueprint/tces/assets/58835213/22d595bb-8e64-4e24-8b40-4d97e062683d

2024-02-05 21:24 UTC, 3milyfz commented on client/src/components/timeline-window-component/clientWindow.jsx
<img width="1204" alt="image" src="https://github.com/uoftblueprint/tces/assets/73791848/14fd11f0-b158-45b7-b3b1-7adc2340382b">

I think you may have forgotten to run `docker compose run react-app npm run format`

2024-02-05 21:28 UTC, 3milyfz requested changes
Great job Selin! Just some minor formatting issues in terminal.

2024-02-07 01:38 UTC, 3milyfz approved these changes, later dismissed

2024-02-09 05:23 UTC, DanielDervishi approved these changes, later dismissed
Thanks for getting this done Selin!

2024-02-09 21:53 UTC, DanielDervishi approved these changes

2024-02-09 21:53 UTC, DanielDervishi commented on client/src/App.jsx
>  // helper functions
Be sure to match the state of app.jsx on your branch with the state of it on main

2024-02-09 22:10 UTC, 3milyfz approved these changes

2024-02-09 22:20 UTC, merged