TCES-34: Implement a button to add more entries to the timeline locally
uoftblueprint/tces pull request #52
Opened 2022-12-04 14:38 UTC by thardchi

Link to issue: https://github.com/uoftblueprint/tces/issues/34
 
# Description

Implemented a functional component called ActivityTimline in src/ActivityTimeline.js I added a text field and a button so users can add more entries to the timeline.

Fixes # 34

## Sample curl
Ignore if PR does not affect an endpoint.
## Response
Ignore if PR does not affect an endpoint.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] I have run `npm run lint:fix`
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings

<img width="1353" alt="Screen Shot 2022-12-04 at 9 36 23 AM" src="https://user-images.githubusercontent.com/74565930/205496842-a150e957-2e93-431d-b547-2819466ad04f.png">
<img width="1352" alt="Screen Shot 2022-12-04 at 9 36 41 AM" src="https://user-images.githubusercontent.com/74565930/205496843-f7b147b7-50b9-4d8e-a0f8-f7badcdab7c3.png">

2022-12-04 21:57 UTC, jordanjanakievski requested changes
Everything is working as demonstrated and expected.

I spoke with Edward and if you can import the feature into App.tsx similar to how Communication was imported and displayed. This will make it easy for people to the code run and find your feature immediately.

2022-12-06 14:34 UTC, ganeshasapu commented on client/src/components/ActivityTimeline.js
> +import React, {useState} from 'react'
I think this file should be a ts file instead of js

2022-12-06 14:37 UTC, ganeshasapu requested changes
Super cool component! Everything works as intended, just one small fix. Also I can't believe I've never used Math.random() to generate ids--it seems like a really good idea.

2022-12-07 02:10 UTC, jordanjanakievski approved these changes
Update to App.tsx looks good.

2022-12-08 19:19 UTC, ganeshasapu approved these changes
Everything looks good!

2023-01-13 01:51 UTC, merged