Job Endpoints (Create, Read, Update, Delete) & Validation Schema
uoftblueprint/tces pull request #55
Opened 2022-12-27 01:32 UTC by helen-li

# Description

Fixes #26, #49  

* Created model, controller, and route for job endpoints (GET, POST, PUT, DELETE)
* Added jobs schema in `conn.ts` and connected it to the jobs collection
* Dependency added in server dir for testing: `@jest-mock/express": "^2.0.1`
* Also ignore the 2 `client` dir files in this PR, I didn't change them but Git argues otherwise lol

## Sample curl for GET
curl --location --request GET 'http://localhost:3001/api/job/63aa4054c792bf4a6580bfd4/'

## Response for GET
{
    "_id": "63aa4054c792bf4a6580bfd4",
    "title": "Test Job XII",
    "creation_date": "2022-07-21T00:00:00.000Z",
    "creator_id": "63bb1f16939f28affbacf5fa",
    "owner_id": "63bb1f16939f28affbacf5fa",
    "timeline": {},
    "employer_id": "63aa1f11cb4203e32ed5264b",
    "pay_per_hour": 22.5,
    "address_id": null,
    "description": null,
    "type": null,
    "expiry_date": null
}

## Sample curl for POST
curl --location --request POST 'http://localhost:3001/api/job' \
--header 'Content-Type: application/json' \
--data-raw '{
    "title": "Test Job XII",
    "creation_date": "2022-07-21",
    "creator_id": "63bb1f16939f28affbacf5fa",
    "timeline": {},
    "employer_id": "63aa1f11cb4203e32ed5264b",
    "pay_per_hour": 22.5
}'

## Response for POST
Successfully created a new job with id 63aa4054c792bf4a6580bfd4 (should be a different ID if you try POST in Postman)

## Sample curl for DELETE
curl --location --request DELETE 'http://localhost:3001/api/job/63aa4054c792bf4a6580bfd4/'

## Response for DELETE
Successfully removed job with id 63aa4054c792bf4a6580bfd4 (whatever ID is in the call)

## Sample curl for PUT
curl --location --request PUT 'http://localhost:3001/api/job/63aa4054c792bf4a6580bfd4/' \
--header 'Content-Type: application/json' \
--data-raw '{
    "title": "Test Updating Job",
    "creation_date": "2022-12-09",
    "creator_id": "63aa1f11cb4203e32ed5264b",
    "owner_id": "63aa40e680f1d80909741d03",
    "timeline": {},
    "employer_id": "63aa1f11cb4203e32ed5264b"
}'

## Response for PUT
Successfully updated job with id 63aa4054c792bf4a6580bfd4 (whatever ID is in the call)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have run `npm run lint:fix`
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works (Delete if frontend)

2023-01-11 18:38 UTC, EclipseIsDead requested changes
really good stuff, small changes

2023-01-11 18:38 UTC, EclipseIsDead commented on server/controllers/job.controller.ts
> +        const id = req?.params?.id;
I think these are unsafe, might be a better TS way of doing it.

2023-01-11 18:38 UTC, EclipseIsDead commented on server/controllers/job.controller.ts
> +            console.log(error);
logger

2023-01-11 18:38 UTC, EclipseIsDead commented on server/src/database/conn.ts
> +const jobSchema = {
ideally this is a separate file

2023-01-11 18:38 UTC, EclipseIsDead commented on server/test/unit/job.test.ts
> +  test('should get job by id successfully', async () => {
use the logger here too for confirmation

2023-01-11 21:18 UTC, helen-li commented on server/test/unit/job.test.ts
> +  test('should get job by id successfully', async () => {
i just added some info logs at the bottom of each test, lmk if this is not what you intended to suggest lol

2023-01-11 21:21 UTC, helen-li commented on server/controllers/job.controller.ts
> +        const id = req?.params?.id;
i just followed mongo's guide for typescript integration & this is the exact code they had lol - lemme dig around a bit more to check for maybe better alternatives

2023-01-15 18:45 UTC, EclipseIsDead commented on server/controllers/job.controller.ts
> +        const id = req?.params?.id;
No worries, double checked the params its all g

2023-01-15 18:46 UTC, EclipseIsDead approved these changes
lgtm

2023-01-15 19:14 UTC, kenneth-miura requested changes
can u move all the backend directories to be inside of src?

2023-01-15 19:19 UTC, jordanjanakievski reviewed
Added a comment in conn.ts that should fix the validation issue

2023-01-15 19:19 UTC, jordanjanakievski commented on server/src/database/conn.ts
> +  await db.command({
`await db.createCollection(JOBS_COLLECTION_NAME, {
		validator: jobSchema,
	});`
Adding this code in the creation of the collection will validate and and result in a successful connection to the backend

2023-01-15 20:49 UTC, kenneth-miura approved these changes
![image](https://user-images.githubusercontent.com/22108651/212566516-c992bd72-75e3-468c-b4e7-8cb34bf4a180.png)

^u

2023-01-17 03:54 UTC, jordanjanakievski approved these changes
Backend connected and requests were successful. Validation looked good.

2023-01-17 04:45 UTC, merged