TCES-54: Employer Add Form
uoftblueprint/tces pull request #56
Opened 2023-01-06 04:33 UTC by thardchi

https://github.com/uoftblueprint/tces/issues/54
# Description

Component lets us add employers. Screenshot below:

Fixes # (54)

## Sample curl
Ignore if PR does not affect an endpoint.
## Response
Ignore if PR does not affect an endpoint.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have run `npm run lint:fix`
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works (Delete if frontend)

![Screen Shot 2023-01-05 at 11 21 57 PM](https://user-images.githubusercontent.com/74565930/210930515-5acc3211-3f6d-41a4-87cd-7e23d49f90e2.png)

2023-01-09 22:36 UTC, helen-li requested changes
Good work!!! Dropped a few comments and suggestions throughout, also I noticed there were multiple layouts in the Employer Add page on our Figma - just wondering if it's within the scope of this ticket to write them all?

2023-01-09 22:36 UTC, helen-li commented on client/src/App.tsx
> +import EpmployerAddForm from "./components/EmployerAddForm";
```suggestion
import EmployerAddForm from "./components/EmployerAddForm";
```
Just a minor typo in this file and in the components file

2023-01-09 22:36 UTC, helen-li commented on client/src/components/EmployerAddForm.tsx
> +                            {/* <Typography margin={0.5} fontSize={11}align="left" color="text.secondary">*Required</Typography> */}
Would recommend removing commented out code if no longer needed to reduce clutter heh

2023-01-09 22:36 UTC, helen-li commented on client/src/components/EmployerAddForm.tsx
> +                            <Grid xs={12} item>
Might be useful to extract these Grid components and write them as a reusable component for you to pass the different labels and placeholders in to reduce repetition & we probably need similar grids for other forms in the future - feel free to take a quick look at #17 `FormTextField.tsx` for an example of what I mean by reusable component & we can chat more about it too

2023-01-09 22:36 UTC, helen-li commented on client/src/components/EmployerAddForm.tsx
> +                {/* Add Seconday Address Button */}
Nice comments!

2023-01-13 02:39 UTC, jordanjanakievski reviewed
Everything worked great and the form looks terrific. I cannot explicitly remember if you were worried about the Province dropdown, but everything looking good on my end as they were left-aligned.

Helen has covered everything that I noticed. Once you make those changes, you can ping me again and I will approve.

2023-01-19 23:46 UTC, helen-li approved these changes
Niceee super good work Thardchi!!!

2023-01-20 02:43 UTC, jordanjanakievski approved these changes
The changes are good

2023-01-20 02:57 UTC, merged