Job listing card
uoftblueprint/tces pull request #62
Opened 2023-01-21 19:37 UTC by annie951977

# Description

Created Job Card component that reads from dummy data. As discussed with Helen, the dummy data JSON file is currently leaving the ObjectID and ISODate objects as strings since there's not an elegant way of dealing with that and those objects end up being read in as strings. 

![job-card](https://user-images.githubusercontent.com/56055607/213884122-acd72ddb-bc19-4bb3-8184-c23e1005c765.png)

Added @mui/icons-material package

Fixes #20 

## Type of change

Please delete options that are not relevant.
- [X] New feature (non-breaking change which adds functionality

# Checklist:

- [ ] I have run `npm run lint:fix`
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation (if required)
- [X] My changes generate no new warnings

2023-01-22 18:26 UTC, thardchi commented on client/src/JobCard/JobCard.css
> +.cardTitle {
since there isn't anything defined in ".cardTitle" you could remove it from this file. Other than that, it all looks good to me!

2023-01-22 18:37 UTC, annie951977 commented on client/src/JobCard/JobCard.css
> +.cardTitle {
ey, true forgot about this. Thanks!

2023-01-25 15:36 UTC, EclipseIsDead requested changes

2023-01-25 15:36 UTC, EclipseIsDead commented on client/src/JobCard/JobCard.tsx
> +        <Box style={{width:659, backgroundColor:"#FFFFFF", margin:"auto", height:"100%" }}>
do we want in file css? might move to seperate styling sheet and generate d.css files

2023-01-25 15:36 UTC, EclipseIsDead commented on client/src/JobCard/JobCard.tsx
> +            <Box paddingTop={4} paddingBottom={1} paddingLeft={3} alignItems="center">
i feel like this can be a mapping from an array to elements?

2023-01-25 15:36 UTC, EclipseIsDead commented on client/src/JobCard/JobCard.tsx
> +            <Box paddingTop={4} paddingBottom={1} paddingLeft={3} alignItems="center">
like all these boxes

2023-01-26 12:22 UTC, annie951977 commented on client/src/JobCard/JobCard.tsx
> +            <Box paddingTop={4} paddingBottom={1} paddingLeft={3} alignItems="center">
@EclipseIsDead can you give an example of what you mean by that?

2023-01-26 12:26 UTC, annie951977 commented on client/src/JobCard/JobCard.tsx
> +        <Box style={{width:659, backgroundColor:"#FFFFFF", margin:"auto", height:"100%" }}>
I'm not sure if it's totally necessary given that a lot of the styling is handled by the mui components? Also it doesn't seem like we've really been maintaining css files for other components

2023-01-29 18:21 UTC, thardchi approved these changes

2023-02-05 18:22 UTC, EclipseIsDead approved these changes
very nice

2023-02-05 19:23 UTC, merged