Address Endpoints, Tests, Schema
uoftblueprint/tces pull request #64
Opened 2023-01-22 18:40 UTC by EclipseIsDead

# Description

4 endpoints:
- Get address + Create address
- Update + Delete

Unit tests (integrated), schema

Address -> 
    street_address
    city
    building_num
    province
    postal_code

Fixes #25, #50 

## Sample curl
Ignore if PR does not affect an endpoint.
## Response
Ignore if PR does not affect an endpoint.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] I have run `npm run lint:fix`
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works (Delete if frontend)

2023-01-29 19:02 UTC, kenneth-miura commented
i am style reviewer, plz add 2 others still

2023-02-03 01:56 UTC, helen-li commented on server/src/database/schemas.ts
> +      building_num: {
schema tells me `building_num` is numeric?

2023-02-03 01:59 UTC, helen-li reviewed
Looks good! Just a few quick comments

2023-02-03 01:59 UTC, helen-li commented on server/src/database/schemas.ts
> +      building_num: {
schema tells me `building_num` is numeric?

2023-02-03 01:59 UTC, helen-li commented on server/src/models/address.model.ts
> +import { deleteAddress } from "../controllers/address.controller";
do you need this import?

2023-02-03 01:59 UTC, helen-li commented on server/src/routes/address.routes.ts
> +addressRouter.use(express.json());
might have to add this router to `index.ts`

2023-02-03 03:00 UTC, jordanjanakievski requested changes
I left a comment under Helen's about router being added to index.ts. I think that will be needed to get the collection initialized in the database. You can copy the previous code snippets in index

2023-02-03 03:11 UTC, kenneth-miura approved these changes
general style looks good

2023-03-11 03:17 UTC, helen-li reviewed
slay, just a few quick necessary fixes with merge conflicts but otherwise looks great

2023-03-11 03:17 UTC, helen-li commented on client/src/App.tsx
> +>>>>>>> d1222a4756d437816347512cab1d7ba9287f4c2c
lol merge conflict be like

2023-03-11 03:17 UTC, helen-li commented on client/src/index.tsx
> +<<<<<<< HEAD
same thing with merge here

2023-03-11 03:17 UTC, helen-li commented on server/src/database/conn.ts
> +<<<<<<< HEAD
a bunch here as well

2023-03-12 18:36 UTC, jordanjanakievski approved these changes
My previous comment was addressed so it looks good to me. Once those merge conflicts are handled that are mentioned by Helen, it will be good to go.

2023-03-12 19:51 UTC, helen-li approved these changes
looks greattt

2023-03-17 00:54 UTC, merged