Page: Add Job Lead
uoftblueprint/tces pull request #72
Opened 2023-01-26 02:51 UTC by helen-li

# Description

Fixes #60 
* Frontend change: added components for the Add Job Lead page (screenshot below)
* Backend change: added Employer GET endpoint to retrieve all docs in the employer collection, also fixed errors caused by #58 due to the collection not being connected in `conn.ts` and `index.ts` in the server dir
* Dependencies: `@mui/x-date-pickers` for date picker component, `date-fns` for handling date objects easier

## Sample curl
curl --location --request GET 'http://localhost:3001/api/employer/'

## Response
[
    {
        "_id": "63d1d945e1130364473e7bfa",
        "name": "Test ",
        "public_name": "Test",
        "contacts": [],
        "creator_id": "63bb1f16939f28affbacf5fa",
        "owner_id": "63bb1f16939f28affbacf5fa",
        "legal_name": null,
        "hr_contacts": null,
        "secondary_address_id": null,
        "initial_contact": null,
        "id": null,
        "timeline": null
    },
    {
        "_id": "63d1d947e1130364473e7bfb",
        "name": "Test 1",
        "public_name": "Test",
        "contacts": [],
        "creator_id": "63bb1f16939f28affbacf5fa",
        "owner_id": "63bb1f16939f28affbacf5fa",
        "legal_name": null,
        "hr_contacts": null,
        "secondary_address_id": null,
        "initial_contact": null,
        "id": null,
        "timeline": null
    }
]

## Screenshot Demo
<img src="https://user-images.githubusercontent.com/85378642/214747638-19d36a66-f988-41e5-99f7-02737967a45d.png"/>

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] I have run `npm run lint:fix`
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works (Delete if frontend)

2023-01-26 13:03 UTC, annie951977 requested changes
The way you format your code makes it very readable, so that's awesome! 

I tried compiling your branch and aside from package lock stuff, I also got these errors. Let me know if you run into these problems as well or if there's something that's weird on my end

![image](https://user-images.githubusercontent.com/56055607/214842279-cc2163e6-fea7-4342-b17c-bee4a43b19f5.png)
![image](https://user-images.githubusercontent.com/56055607/214842318-ec379425-dc73-4729-9b32-263f749cbf80.png)
![image](https://user-images.githubusercontent.com/56055607/214842355-02580c37-2d45-4f54-b769-dc1a5b329704.png)

2023-01-26 16:44 UTC, helen-li commented on client/src/App.tsx
> +				{AddJobLead()}
Just for testing! I'm not entirely sure whether router is set up for client yet to navigate between pages so I just threw it in here, can totally remove before I merge

2023-01-26 16:48 UTC, helen-li commented
> The way you format your code makes it very readable, so that's awesome!
> 
> I tried compiling your branch and aside from package lock stuff, I also got these errors. Let me know if you run into these problems as well or if there's something that's weird on my end
> 
> ![image](https://user-images.githubusercontent.com/56055607/214842627-619c53b9-4f80-4714-b560-483cb7a5ff68.png) ![image](https://user-images.githubusercontent.com/56055607/214842318-ec379425-dc73-4729-9b32-263f749cbf80.png) ![image](https://user-images.githubusercontent.com/56055607/214842355-02580c37-2d45-4f54-b769-dc1a5b329704.png)

@Manal-jpg Could you try compiling on your end and see if you can reproduce these errors? I somehow could not reproduce the same warnings on my system and am concerned there's something wrong with my setup. Thanks!

For reference, my output just looks like this: 
<img src="https://user-images.githubusercontent.com/85378642/214896874-e01554f5-e6d1-4bac-af0b-b7aa956699d0.png">

2023-01-30 08:31 UTC, Manal-jpg approved these changes
I've finally reviewed the PR, sorry for the long wait. Everything looks great to me. I didn't get the errors Annie was having, and it was running on my computer without a problem (there was a small package error that Ganesh addressed on Slack). As for the employer conn.ts problem, I just realized that I accidentally removed my changes for that file while solving merge conflicts so sorry about that, and tysm for fixing it.

2023-02-07 22:36 UTC, edwardhuahan commented
I just compiled everything, it gave me a few warnings but no errors

![image](https://user-images.githubusercontent.com/17802344/217382196-f94b1997-9d2c-428a-9dff-639f25913ad5.png)

2023-02-07 22:37 UTC, edwardhuahan commented
Awesome job! It looks great, I think it'd be best to style your components using css files like we decided instead of the sx prop but just to save time I think it's fine this time

2023-02-07 22:38 UTC, edwardhuahan approved these changes
Make sure to make external css files next time for styling

2023-02-09 12:18 UTC, annie951977 approved these changes
Other that the previously addressed issues which look like are not replicable, looks good to me!

2023-02-09 20:08 UTC, merged