Job Fields & Timeline Endpoints
uoftblueprint/tces pull request #86
Opened 2023-02-04 06:07 UTC by helen-li

# Description

Fixes #78, #81 

* No new dependencies added
* Added 2 PATCH endpoints to add entries to the embedded timeline object under Jobs and Employers collections (#81 ticket info is actually a bit outdated @kenneth-miura)
* Added timeline schema and model 
* Added new job fields (#78 also slightly outdated, need to add both NOC and hours per week fields)

## PATCH Job Timeline Sample Curl
curl --location --request PATCH 'http://localhost:3001/api/job/63dd963b33698e7e9f8588b9/timeline' \
--header 'Content-Type: application/json' \
--data-raw '{
    "text": "Test 2 Text!",
    "category": "JOBS",
    "title": "Test Title 2",
    "timestamp": "2023-1-22"
}'

## PATCH Job Timeline Sample Response
Successfully updated the timeline field of job with id 63dd963b33698e7e9f8588b9

### Same curl and response for PATCH Employer Timeline (just different request URL).

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] I have run `npm run lint:fix`
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works (Delete if frontend)

2023-02-04 16:48 UTC, ganeshasapu commented on server/src/database/schemas.ts
> +        additionalProperties: false,
I did not know about this, I should include it in my schemas as well

2023-02-04 16:50 UTC, ganeshasapu commented on server/src/database/schemas.ts
> +      timeline: timelineSchema,
Ok i did not know you could do this lol, i need to do this as well

2023-02-04 17:09 UTC, ganeshasapu commented on server/src/controllers/employer.controller.ts
> +          res.status(304).send(e.message);
I think this might need to be a 404 code, https://github.com/uoftblueprint/tces/pull/82#discussion_r1095313308

2023-02-04 17:12 UTC, ganeshasapu approved these changes
epic PR overall -- i just looked over everything and it looks good to me, i think just one small http status code tweak

2023-02-05 19:47 UTC, kenneth-miura requested changes
make TimelineUtil.ts in Timeline dir

2023-02-05 21:36 UTC, kenneth-miura approved these changes
very cool

2023-02-09 21:07 UTC, thardchi approved these changes
looks great!

2023-02-09 21:12 UTC, merged