Dummy pages
uoftblueprint/tces pull request #88
Opened 2023-02-05 18:31 UTC by jordanjanakievski

# Description

Creates the dashboard, job, and employer pages

![Screenshot 2023-02-04 at 16 40 49](https://user-images.githubusercontent.com/41130718/216837955-5d93c0c5-f0c0-477d-a35b-d7a911546cdf.png)
![Screenshot 2023-02-04 at 16 41 00](https://user-images.githubusercontent.com/41130718/216837956-48f3fc38-2c28-4f57-9e7f-49e4064eaa75.png)
![Screenshot 2023-02-04 at 22 26 15](https://user-images.githubusercontent.com/41130718/216837958-c2391004-d8ee-4834-882d-d84dfff9fcd4.png)
![Screenshot 2023-02-04 at 22 27 56](https://user-images.githubusercontent.com/41130718/216837964-91c4304b-ede2-4cf8-a762-b97fbabd55c8.png)

Fixes #40, #75, #76

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] I have run `npm run lint:fix`
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if required)
- [X] My changes generate no new warnings

2023-02-12 18:56 UTC, thardchi approved these changes
Great work! Everything looks good to me!

2023-02-12 19:13 UTC, edwardhuahan requested changes

2023-02-12 19:13 UTC, edwardhuahan commented on client/package.json
> +	"name": "client",
Make sure to fix the tabs here

2023-02-12 19:13 UTC, edwardhuahan commented on client/src/components/ClientCard/ClientCard.tsx
> +				<Box paddingTop={2} paddingBottom={2} paddingLeft={2}>
I noticed you use this structure a lot in the code, can you quickly turn this into a component for readability?

2023-02-12 19:13 UTC, edwardhuahan commented on client/src/components/EmployerContactCard/EmployerContactCard.tsx
> +				<Box paddingTop={2} paddingBottom={2} paddingLeft={2}>
Same thing as the card recommendation

2023-02-12 19:13 UTC, edwardhuahan commented on client/src/components/EmployerInfoCard/EmployerInfoCard.tsx
> +				<Box paddingTop={2} paddingBottom={2} paddingLeft={2}>
Same thing as previous comment ^

2023-02-12 19:13 UTC, edwardhuahan commented on client/src/components/EmployerJobLeadsCard/EmployerJobLeadsCard.tsx
> +			<Box
Same thing as previous comment ^

2023-02-12 19:13 UTC, edwardhuahan commented on client/src/pages/DashboardPage/Dashboard.tsx
> +					<Card className="dashboard-card" id="dashboard-card">
Can you make this a component in the same file since you're reusing this component a lot? Use a const for these reused functions but declare the main one as export default function

2023-02-12 19:22 UTC, annie951977 reviewed
Looks good overall!

Style wise I think we're trying to enforce the declaring react component style that doesn't have the arrow in it https://github.com/uoftblueprint/tces/wiki/React-StyleGuide

2023-02-13 13:49 UTC, edwardhuahan commented on client/src/components/CardComponents/CardRow.tsx
> +							<Link href="*">{rowValue}</Link>
Because there's only one tiny line of difference, I would actually take advantage of [React's conditional rendering methods](https://reactjs.org/docs/conditional-rendering.html) and write this if-statement inline as:
```jsx
<Typography gutterBottom variant="body1" align="left">
	{link 
		? <Link href="*">{rowValue}</Link>
		: {rowValue}
	}
</Typography>
```
To shrink the file size even more and increase readability

2023-02-13 13:49 UTC, edwardhuahan commented on client/src/components/CardComponents/CardRowChip.tsx
> +									<Link href="*">{rowValue}</Link>
Same thing here ^

2023-02-13 13:49 UTC, edwardhuahan commented on client/src/components/CardComponents/CardRowCopy.tsx
> +							<Link href="*">{rowValue}</Link>
Same thing here ^

2023-02-17 16:25 UTC, edwardhuahan approved these changes
Awesome job! I think this is ready

2023-02-17 16:47 UTC, merged